# Generated by Django 5.1.6 on 2025-02-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0005_rename_follows_profile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='follows',
        ),
    ]
